### ISSUE TITLE
Cannot support DSM7.1

### ISSUE THREAD

**Issue by JimmyChung208** [jboxberger/synology-gitlab-ce#11]
Do you plane to support DSM7.1?
The DSM7.1's docker is change name to "container manager" so I cannot install Synology-girl lab-ce anymore.

**Comment by JimmyChung208** [comment]
rebuild spk to slove this issue.
Thanks.

**Comment by jakeslee** [comment]
how to rebuild spk? I used build.sh scripts to build, but still got error message

**Comment by jboxberger** [comment]
No problem, which SPK you're trying to rebuild. Classic or advanced?

**Comment by jboxberger** [comment]
> how to rebuild spk? I used build.sh scripts to build, but still got error message

Ive uploaed new releases. Please feel fre to use them :-)
