### ISSUE TITLE
build clarifications

### ISSUE THREAD

**Issue by caco3** [jboxberger/synology-gitlab-ce#2]
It is not clear to me:
Is it required to build on a Synology NAS or can we build on any Linux system?
Could you clarify this in the readme?

**Comment by jboxberger** [comment]
You can build on any linux, you just need jq installed. :-)
I will clarify it in the readme :-)

**Comment by caco3** [comment]
great!

Next question:
Is there a reason the version on the build script is not treated the same as the other 2 parameters? I would change it to `--version` so it is consistent.

**Comment by caco3** [comment]
as is now, it is actually rater odd:
if you build without parameter, it suggest to use the latest version by default. how ever if you appen one of the options, the version must explicitly be noted (although one might not now which ones are available).
I therefore would be nice to show all available version.

=Y I wil try to see if I find a way for this

**Comment by jboxberger** [comment]
i have a way, for that already in code, but i take only the latest.

https://github.com/jboxberger/synology-gitlab-ce/blob/4a4025c4d1deb49d6c5e797f9b9c9b9106c75267/build#L23

**Comment by jboxberger** [comment]
I have already a list solution, i can list the lastest 8 - 10 (for more there is paging required and its unnessesary) versions and make them selectable if this is that you see. ive done that already in the past so i can implement it quite easyily althoug its a hard and fancy one task :-)

**Comment by caco3** [comment]
I also have it almost ready :)

**Comment by caco3** [comment]
here you go :)
https://github.com/jboxberger/synology-gitlab-ce/pull/3

**Comment by jboxberger** [comment]
I've taken your approach and improved it a bit. The version is now optional and when you not provide it you will get automatically a list of 9 latest versions to select from. I think this is more intuitive than a simple listing command and hope you like it.

I've also done some cherry-picking on your PR and modified it. You will find the find the final result in the master

Clarification: done
Unify Arguments: done 

Thank you four your contribution.
