### ISSUE TITLE
Unclear Instructions

### ISSUE THREAD

**Issue by jamsoft** [jboxberger/synology-gitlab-ce#8]
I'm looking at this and not really getting how to use it.

I'm looking to install GitLab on a new diskstation. I had been using the old Synology package on a 918+ but the lack of attention from Synology is a shame.

The synology-gitlab-ce-15.1.2-dsm7-advanced.spk. What do I do with this file? It's not mentioned in your instructions at all. Is this a package that needs installing on the NAS?

Your commands like 'cd /var/packages/synology-gitlab-ce ... ' Are these commands being run on the Synology?

Have to admit this is all a little confusing.

**Comment by jboxberger** [comment]
Hi, sorry that the instructions are not clear enough for you.  But usually you install an SPK on the synology over DSM. This the way you nortmaly install packages that are not in any repository. Sindce Gitlab is an advanced tool i justr assume that this is known.

On The Advanced Package you end up with some shell scripts witch you need to execute on your Syynology over SSH. The final command is shown during Installation and can be copied with STRG+C - also everything docukmented in the readme.md

See also "After instalkl you need to login... " in the screenshot, "this approach bypass the root privileges limitation of the DSM by running the setup over ssh." and "very simplistic package, installation and basic configuration over DSM, no ssh or root privileges required."

You could have answered your question by googeling "how to install SPK on synology" and reading the documentation :-)

Kind Regards
